default_environment: default
environments:
    default:
        connections:
            clickhouse:
                - name: clickhouse-default
                  username: username
                  password: password
                  host: 127.0.0.1
                  port: 19000
                  database: default
            github:
                - name: github
                  access_token: ${GITHUB_TOKEN}
                  owner: arsalann
                  repo: bruin-clickhouse
            bruin:
                - name: bruin-cloud
                  api_token: ${BRUIN_CLOUD_API_TOKEN}
